openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Sample API'
  description: Weather on Mars

servers:
  - url: https://api.nasa.gov
    description: Nasa Api
paths:
  /insight_weather/:
    get:
      summary: Mars Weather
      parameters:
        - name: api_key
          description: The unique api key
          in: query
          required: true
          schema:
            type: string
          example: 'IxpTyqs8LnclBrUq88cIdf99zftbzPgHYbmEzb1V'
        - name: feedtype
          description: The feed type
          in: query
          required: true
          schema:
            type: string
          example: 'json'
        - name: ver
          description: The api version
          in: query
          required: true
          schema:
            type: string
          example: '1.0'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
